# Generated by Django 3.2.7 on 2021-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('comment', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
