# Generated by Django 3.2.7 on 2021-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210925_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
