# Generated by Django 3.2.7 on 2021-10-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
